%YAML 1.2
---
app:
  max_default_priority_queue_size: 100 # max size of the default priority entry queue TODO choose a good limit
  max_high_priority_queue_size: 100 # max size of the high priority entry queue TODO choose a good limit
  process_interval: 60 # interval between queues processment TODO choose a good limit
test:
  max_default_priority_queue_size: 50 # max size of the default priority entry queue
  max_high_priority_queue_size: 50 # max size of the high priority entry queue
  process_interval: 5 # interval between queues processment
...
