%YAML 1.2
---
app:
  process_interval: 60
  endpoint: "<endpoint>"
  username: "<username>"
  password: "<password>"
  max_activities: 50
test:
  process_interval: 60
  endpoint: "<endpoint>"
  username: "<username>"
  password: "<password>"
  max_activities: 50
...
